services:
#    teamspeack.example:
#        class: TeamspeackBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    teamspeack.teamspeackadapater:
        class: TeamspeackBundle\TeamspeackAdapater\TeamspeackAdapter
        arguments:
          - %database_password%