<?php

namespace ForumBundle\Repository;

/**
 * ForumCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
